version: '3.8'

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: titanic_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: titanic_ui
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - API_URL=http://fastapi:8000/predict
    restart: always
